name = "audiencias20bpm-api"
main = "src/index.js"
compatibility_date = "2026-09-17"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "audiencias20bpm"
database_id = "56802b05-5cdb-4f9d-8ef5-e6402294ac97"

[[r2_buckets]]
binding = "DOCUMENTOS"
bucket_name = "audiencias20bpm-documentos"

[vars]
APP_NAME = "Sistema de Audiências"
APP_VERSION = "0.11.4"
TIMEZONE = "America/Belem"
FRONTEND_ORIGIN = "https://audiencias20bpm-github-io.audiencias-20-bpm.workers.dev,http://localhost:8080"
SESSION_MINUTES = "30"
