PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS audiencias (id TEXT PRIMARY KEY,codigo TEXT,processo TEXT,assunto TEXT,destinatario_id TEXT,data_hora TEXT,timezone TEXT,local TEXT,modalidade TEXT,link TEXT,observacoes TEXT,oficio_drive_id TEXT,status TEXT,criado_em TEXT,criado_por TEXT,atualizado_em TEXT,atualizado_por TEXT);
CREATE INDEX IF NOT EXISTS idx_audiencias_data ON audiencias(data_hora);
CREATE INDEX IF NOT EXISTS idx_audiencias_status ON audiencias(status);
CREATE TABLE IF NOT EXISTS destinatarios (id TEXT PRIMARY KEY,nome TEXT,telefone TEXT,identificacao TEXT,unidade TEXT,status TEXT,criado_em TEXT,atualizado_em TEXT,rg TEXT,cpf TEXT,posto_graduacao TEXT);
CREATE INDEX IF NOT EXISTS idx_dest_nome ON destinatarios(nome);
CREATE INDEX IF NOT EXISTS idx_dest_rg ON destinatarios(rg);
CREATE INDEX IF NOT EXISTS idx_dest_cpf ON destinatarios(cpf);
CREATE TABLE IF NOT EXISTS audiencia_destinatarios (id TEXT PRIMARY KEY,audiencia_id TEXT NOT NULL,destinatario_id TEXT NOT NULL,status TEXT,criado_em TEXT,criado_por TEXT,FOREIGN KEY(audiencia_id) REFERENCES audiencias(id),FOREIGN KEY(destinatario_id) REFERENCES destinatarios(id));
CREATE INDEX IF NOT EXISTS idx_ad_audiencia ON audiencia_destinatarios(audiencia_id);
CREATE TABLE IF NOT EXISTS usuarios (id TEXT PRIMARY KEY,nome TEXT,login TEXT UNIQUE NOT NULL,perfil TEXT,status TEXT,senha_hash TEXT,salt TEXT,ultimo_login TEXT,criado_em TEXT,atualizado_em TEXT,tipo_conta TEXT,troca_senha_pendente INTEGER DEFAULT 0,tentativas_falhas INTEGER DEFAULT 0,bloqueado_ate TEXT,ultimo_erro_login TEXT,ultimo_ip_contexto TEXT);
CREATE TABLE IF NOT EXISTS sessoes (token_hash TEXT PRIMARY KEY,usuario_id TEXT NOT NULL,criado_em TEXT NOT NULL,expira_em TEXT NOT NULL,ultimo_uso_em TEXT NOT NULL,revogada_em TEXT,FOREIGN KEY(usuario_id) REFERENCES usuarios(id));
CREATE INDEX IF NOT EXISTS idx_sessoes_usuario ON sessoes(usuario_id);
CREATE TABLE IF NOT EXISTS passkeys (credential_id TEXT PRIMARY KEY,usuario_id TEXT NOT NULL,public_key TEXT NOT NULL,sign_count INTEGER DEFAULT 0,transports TEXT,dispositivo TEXT,rp_id TEXT NOT NULL,criado_em TEXT NOT NULL,ultimo_uso_em TEXT,revogada_em TEXT,FOREIGN KEY(usuario_id) REFERENCES usuarios(id));
CREATE INDEX IF NOT EXISTS idx_passkeys_usuario ON passkeys(usuario_id);
CREATE TABLE IF NOT EXISTS webauthn_challenges (id TEXT PRIMARY KEY,usuario_id TEXT,purpose TEXT NOT NULL,challenge TEXT NOT NULL,expira_em TEXT NOT NULL,usado_em TEXT);
CREATE TABLE IF NOT EXISTS configuracoes (chave TEXT PRIMARY KEY,valor TEXT,atualizado_em TEXT,atualizado_por TEXT);
CREATE TABLE IF NOT EXISTS oficios (id TEXT PRIMARY KEY,audiencia_id TEXT,destinatario_id TEXT,numero INTEGER,ano INTEGER,status TEXT,drive_id TEXT,data_emissao TEXT,destino_judicial TEXT,trecho_opcional TEXT,posto_graduacao TEXT,dados_json TEXT,pdf_nome TEXT,processo_pdf_drive_id TEXT,processo_pdf_nome TEXT,criado_em TEXT,criado_por TEXT,atualizado_em TEXT,enviado_em TEXT,confirmado_em TEXT,r2_pdf_key TEXT,r2_processo_key TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS idx_oficios_numero_ano ON oficios(numero,ano);
CREATE TABLE IF NOT EXISTS notificacoes (id TEXT PRIMARY KEY,chave_idempotencia TEXT UNIQUE,audiencia_id TEXT,destinatario_id TEXT,oficio_id TEXT,tipo TEXT,telefone TEXT,template TEXT,mensagem TEXT,token_hash TEXT,data_programada TEXT,status TEXT,tentativas INTEGER DEFAULT 0,provider TEXT,wamid TEXT,ultimo_erro_codigo TEXT,ultimo_erro_resumo TEXT,criado_em TEXT,criado_por TEXT,processando_em TEXT,simulado_em TEXT,enviado_em TEXT,confirmado_em TEXT,atualizado_em TEXT);
CREATE TABLE IF NOT EXISTS eventos (id TEXT PRIMARY KEY,audiencia_id TEXT,notificacao_id TEXT,tipo TEXT,timestamp TEXT,wamid TEXT,origem TEXT,dados TEXT);
CREATE TABLE IF NOT EXISTS auditoria (id TEXT PRIMARY KEY,timestamp TEXT,usuario_id TEXT,acao TEXT,entidade TEXT,registro_id TEXT,ip_contexto TEXT,dados_anteriores TEXT,dados_novos TEXT,resultado TEXT);
