const json=(body,status=200,origin='*')=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type','cache-control':'no-store'}});
const ok=(data={},mensagem='OK',origin='*')=>json({success:true,sucesso:true,data,mensagem},200,origin);
const fail=(codigo,mensagem,status=400,origin='*')=>json({success:false,sucesso:false,codigo,mensagem},status,origin);
const clean=v=>String(v??'').trim();
const now=()=>new Date().toISOString();
const b64u=bytes=>{let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const randomToken=(n=32)=>b64u(crypto.getRandomValues(new Uint8Array(n)));
async function sha256(v){return b64u(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v)))))}
function originFor(req,env){const o=req.headers.get('Origin')||'';return !o||o===env.FRONTEND_ORIGIN? (o||env.FRONTEND_ORIGIN):env.FRONTEND_ORIGIN}
async function session(env,token){if(!token)return null;const h=await sha256(token);const row=await env.DB.prepare(`SELECT s.*,u.id uid,u.nome,u.login,u.perfil,u.status,u.tipo_conta,u.troca_senha_pendente FROM sessoes s JOIN usuarios u ON u.id=s.usuario_id WHERE s.token_hash=? AND s.revogada_em IS NULL AND s.expira_em>?`).bind(h,now()).first();if(!row)return null;const exp=new Date(Date.now()+Number(env.SESSION_MINUTES||30)*60000).toISOString();await env.DB.prepare('UPDATE sessoes SET ultimo_uso_em=?,expira_em=? WHERE token_hash=?').bind(now(),exp,h).run();return {row,token,exp}}
function userDto(r){return {id:r.uid||r.id,nome:r.nome,login:r.login,perfil:r.perfil,tipo_conta:r.tipo_conta,troca_senha_pendente:Boolean(r.troca_senha_pendente)}}
async function routeHealth(env,o){const x=await env.DB.prepare('SELECT 1 ok').first();return ok({app:env.APP_NAME,version:env.APP_VERSION,d1:Boolean(x&&x.ok),r2:Boolean(env.DOCUMENTOS)},'API Cloudflare operacional.',o)}
async function routeSession(d,env,o){const s=await session(env,clean(d.token));if(!s)return fail('SESSAO_INVALIDA','Sessão inválida ou expirada.',401,o);return ok({usuario:userDto(s.row),sessao:{token:s.token,expira_em:s.exp}},'Sessão válida.',o)}
async function routeLogout(d,env,o){const token=clean(d.token);if(token)await env.DB.prepare('UPDATE sessoes SET revogada_em=? WHERE token_hash=?').bind(now(),await sha256(token)).run();return ok({},'Sessão encerrada.',o)}
async function requireSession(d,env,o){const s=await session(env,clean(d.token));if(!s)throw Object.assign(new Error('Sessão inválida ou expirada.'),{code:'SESSAO_INVALIDA',status:401,origin:o});return s}
async function listAudiencias(d,env,o){await requireSession(d,env,o);const r=await env.DB.prepare('SELECT * FROM audiencias ORDER BY data_hora ASC').all();return ok({audiencias:r.results||[]},'Audiências consultadas.',o)}
async function listDestinatarios(d,env,o){await requireSession(d,env,o);const r=await env.DB.prepare('SELECT * FROM destinatarios ORDER BY nome COLLATE NOCASE').all();return ok({destinatarios:r.results||[]},'Destinatários consultados.',o)}
async function listUsuarios(d,env,o){await requireSession(d,env,o);const r=await env.DB.prepare(`SELECT id,nome,login,perfil,status,ultimo_login,criado_em,atualizado_em,tipo_conta,troca_senha_pendente,tentativas_falhas,bloqueado_ate FROM usuarios ORDER BY nome COLLATE NOCASE`).all();return ok({usuarios:r.results||[]},'Usuários consultados.',o)}
async function biometriaStatus(d,env,o){const s=await requireSession(d,env,o);const r=await env.DB.prepare('SELECT credential_id,dispositivo,criado_em,ultimo_uso_em FROM passkeys WHERE usuario_id=? AND revogada_em IS NULL ORDER BY criado_em DESC').bind(s.row.usuario_id).all();return ok({disponivel:true,credenciais:r.results||[]},'Status da biometria consultado.',o)}
async function passkeyOptions(d,env,o,purpose){let uid=null;if(purpose==='register'){const s=await requireSession(d,env,o);uid=s.row.usuario_id}const challenge=randomToken(32),id=crypto.randomUUID(),exp=new Date(Date.now()+5*60000).toISOString();await env.DB.prepare('INSERT INTO webauthn_challenges(id,usuario_id,purpose,challenge,expira_em) VALUES(?,?,?,?,?)').bind(id,uid,purpose,challenge,exp).run();return ok({challenge_id:id,challenge,rp_id:new URL(env.FRONTEND_ORIGIN).hostname,timeout:60000,user_verification:'required'},'Desafio WebAuthn criado.',o)}
async function dispatch(d,env,o){switch(clean(d.action)){case 'health':return routeHealth(env,o);case 'session':return routeSession(d,env,o);case 'logout':return routeLogout(d,env,o);case 'audiencias_list':return listAudiencias(d,env,o);case 'destinatarios_list':return listDestinatarios(d,env,o);case 'usuarios_list':return listUsuarios(d,env,o);case 'biometria_status':return biometriaStatus(d,env,o);case 'passkey_register_options':return passkeyOptions(d,env,o,'register');case 'passkey_login_options':return passkeyOptions(d,env,o,'login');default:return fail('ROTA_EM_MIGRACAO','Rota ainda não ativada no backend Cloudflare: '+clean(d.action),501,o)}}
export default {async fetch(req,env){const o=originFor(req,env);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':o,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type'}});try{if(req.method==='GET'){const u=new URL(req.url);return dispatch({action:u.searchParams.get('action')||'health'},env,o)}if(req.method!=='POST')return fail('METODO_INVALIDO','Método não permitido.',405,o);const d=await req.json().catch(()=>({}));return await dispatch(d,env,o)}catch(e){return fail(e.code||'ERRO_INTERNO',e.message||'Erro interno.',e.status||500,o)}}};
