const json=(body,status=200,origin='*')=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type','cache-control':'no-store'}});
const ok=(data={},mensagem='OK',origin='*')=>json({success:true,sucesso:true,data,mensagem},200,origin);
const fail=(codigo,mensagem,status=400,origin='*')=>json({success:false,sucesso:false,codigo,mensagem},status,origin);
const clean=v=>String(v??'').trim(), upper=v=>clean(v).toUpperCase(), digits=v=>clean(v).replace(/\D+/g,''), now=()=>new Date().toISOString();
const enc=new TextEncoder();
const b64u=bytes=>{let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const hex=bytes=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
const randomToken=(n=48)=>b64u(crypto.getRandomValues(new Uint8Array(n)));
async function sha256Hex(v){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(v)))))}
async function hmacHex(secret,value){const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(value))))}
async function legacyPasswordHash(password,salt,pepper){let material=String(password)+':'+String(salt)+':'+String(pepper);for(let i=0;i<10000;i++)material=await sha256Hex(material);return material}
function safeEqual(a,b){a=String(a||'');b=String(b||'');let d=a.length^b.length,n=Math.max(a.length,b.length);for(let i=0;i<n;i++)d|=(i<a.length?a.charCodeAt(i):0)^(i<b.length?b.charCodeAt(i):0);return d===0}
function originFor(req,env){const o=req.headers.get('Origin')||'';const allowed=String(env.FRONTEND_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean);return !o||allowed.includes(o)?(o||allowed[0]||'*'):(allowed[0]||'*')}
async function tokenHash(env,token){if(!env.SESSION_SECRET)throw new Error('SESSION_SECRET não configurado.');return hmacHex(env.SESSION_SECRET,token)}
async function getSession(env,token){if(!token)return null;const h=await tokenHash(env,token);const row=await env.DB.prepare(`SELECT s.*,u.id uid,u.nome,u.login,u.perfil,u.status,u.tipo_conta,u.troca_senha_pendente FROM sessoes s JOIN usuarios u ON u.id=s.usuario_id WHERE s.token_hash=? AND s.revogada_em IS NULL AND s.expira_em>?`).bind(h,now()).first();if(!row)return null;const exp=new Date(Date.now()+Number(env.SESSION_MINUTES||30)*60000).toISOString();await env.DB.prepare('UPDATE sessoes SET ultimo_uso_em=?,expira_em=? WHERE token_hash=?').bind(now(),exp,h).run();return {row,token,exp}}
function userDto(r){return {id:r.uid||r.id,nome:r.nome,login:r.login,perfil:r.perfil,tipo_conta:r.tipo_conta||'',troca_senha_pendente:Boolean(r.troca_senha_pendente)}}
async function requireSession(d,env,o){const s=await getSession(env,clean(d.token));if(!s)throw Object.assign(new Error('Sessão inválida ou expirada.'),{code:'SESSAO_INVALIDA',status:401,origin:o});return s}
function requireAdmin(s){const p=upper(s.row.perfil);if(p!=='DEV'&&p!=='ADMINISTRADOR')throw Object.assign(new Error('Acesso negado.'),{code:'ACESSO_NEGADO',status:403});}
const withExp=(s,data={})=>Object.assign({},data,{expira_em:s.exp});
async function audit(env,s,acao,entidade,id,before=null,after=null,result='OK'){try{await env.DB.prepare('INSERT INTO auditoria(id,timestamp,usuario_id,acao,entidade,registro_id,dados_anteriores,dados_novos,resultado) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),now(),s?.row?.usuario_id||s?.row?.uid||null,acao,entidade,id||null,before?JSON.stringify(before):null,after?JSON.stringify(after):null,result).run()}catch(_){}}
function bytesFromBase64(v){const b=atob(String(v||''));const a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function r2Base64(env,key){if(!key)return null;const obj=await env.DOCUMENTOS.get(key);if(!obj)return null;const bytes=new Uint8Array(await obj.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return {base64:btoa(bin),mime:obj.httpMetadata?.contentType||'application/octet-stream',nome:obj.customMetadata?.nome||key.split('/').pop()}}
async function configMap(env){const r=await env.DB.prepare('SELECT chave,valor FROM configuracoes').all(),m={};for(const x of r.results||[])m[x.chave]=x.valor;return m}
async function setConfig(env,s,key,value){await env.DB.prepare(`INSERT INTO configuracoes(chave,valor,atualizado_em,atualizado_por) VALUES(?,?,?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor,atualizado_em=excluded.atualizado_em,atualizado_por=excluded.atualizado_por`).bind(key,String(value??''),now(),s.row.usuario_id).run()}
async function createSessionForUser(env,u){const token=randomToken(),created=now(),exp=new Date(Date.now()+Number(env.SESSION_MINUTES||30)*60000).toISOString(),th=await tokenHash(env,token);await env.DB.prepare('INSERT INTO sessoes(token_hash,usuario_id,criado_em,expira_em,ultimo_uso_em) VALUES(?,?,?,?,?)').bind(th,u.id,created,exp,created).run();return {token,expira_em:exp,duracao_segundos:Number(env.SESSION_MINUTES||30)*60}}
async function routeHealth(env,o){const x=await env.DB.prepare('SELECT COUNT(*) total FROM usuarios').first();return ok({app:env.APP_NAME,version:env.APP_VERSION,d1:true,usuarios:Number(x?.total||0),r2:Boolean(env.DOCUMENTOS)},'API Cloudflare operacional.',o)}
async function routeLogin(d,env,o){const login=clean(d.login).toLowerCase(),password=String(d.senha||'');if(!login||!password)return fail('CREDENCIAIS_INVALIDAS','Login ou senha inválidos.',401,o);if(!env.PASSWORD_PEPPER||!env.SESSION_SECRET)return fail('CONFIGURACAO_INCOMPLETA','Segredos de autenticação não configurados.',503,o);const u=await env.DB.prepare('SELECT * FROM usuarios WHERE lower(login)=? LIMIT 1').bind(login).first();if(!u){await legacyPasswordHash(password,'0000000000000000000000000000000000000000000000000000000000000000',env.PASSWORD_PEPPER);return fail('CREDENCIAIS_INVALIDAS','Login ou senha inválidos.',401,o)}if(upper(u.status)!=='ATIVO')return fail('ACESSO_INDISPONIVEL','Não foi possível realizar o acesso.',403,o);if(u.bloqueado_ate&&Date.parse(u.bloqueado_ate)>Date.now())return fail('ACESSO_TEMPORARIAMENTE_BLOQUEADO','Acesso temporariamente bloqueado. Tente novamente mais tarde ou contate o administrador.',423,o);const calc=await legacyPasswordHash(password,u.salt,env.PASSWORD_PEPPER);if(!safeEqual(calc,u.senha_hash)){const attempts=Number(u.tentativas_falhas||0)+1,blocked=attempts>=5?new Date(Date.now()+15*60000).toISOString():null;await env.DB.prepare('UPDATE usuarios SET tentativas_falhas=?,bloqueado_ate=?,ultimo_erro_login=?,atualizado_em=? WHERE id=?').bind(attempts,blocked,'CREDENCIAIS_INVALIDAS',now(),u.id).run();return fail(blocked?'ACESSO_TEMPORARIAMENTE_BLOQUEADO':'CREDENCIAIS_INVALIDAS',blocked?'Acesso temporariamente bloqueado. Tente novamente mais tarde ou contate o administrador.':'Login ou senha inválidos.',blocked?423:401,o)}const sess=await createSessionForUser(env,u),t=now();await env.DB.prepare('UPDATE usuarios SET tentativas_falhas=0,bloqueado_ate=NULL,ultimo_erro_login=NULL,ultimo_login=?,atualizado_em=? WHERE id=?').bind(t,t,u.id).run();return ok({usuario:userDto(u),sessao:sess},'Login realizado com sucesso.',o)}
async function routeSession(d,env,o){const s=await getSession(env,clean(d.token));if(!s)return fail('SESSAO_INVALIDA','Sessão inválida ou expirada.',401,o);return ok({usuario:userDto(s.row),sessao:{token:s.token,expira_em:s.exp,duracao_segundos:Number(env.SESSION_MINUTES||30)*60},expira_em:s.exp},'Sessão válida.',o)}
async function routeLogout(d,env,o){const token=clean(d.token);if(token)await env.DB.prepare('UPDATE sessoes SET revogada_em=? WHERE token_hash=?').bind(now(),await tokenHash(env,token)).run();return ok({},'Sessão encerrada.',o)}
async function listAudiencias(d,env,o){const s=await requireSession(d,env,o);const r=await env.DB.prepare(`SELECT a.* FROM audiencias a ORDER BY a.data_hora ASC`).all();const items=r.results||[];for(const a of items){const x=await env.DB.prepare(`SELECT d.* FROM audiencia_destinatarios ad JOIN destinatarios d ON d.id=ad.destinatario_id WHERE ad.audiencia_id=? ORDER BY d.nome COLLATE NOCASE`).bind(a.id).all();a.destinatarios=x.results||[]}return ok(withExp(s,{audiencias:items}),'Audiências consultadas.',o)}
async function listDestinatarios(d,env,o){const s=await requireSession(d,env,o);const r=await env.DB.prepare('SELECT * FROM destinatarios ORDER BY nome COLLATE NOCASE').all();return ok(withExp(s,{destinatarios:r.results||[]}),'Destinatários consultados.',o)}
async function lookupDestinatarios(d,env,o){const s=await requireSession(d,env,o),tipo=upper(d.tipo),v=clean(d.valor);let q;if(tipo==='RG')q=await env.DB.prepare('SELECT * FROM destinatarios WHERE rg=? OR identificacao=? LIMIT 10').bind(digits(v),digits(v)).all();else if(tipo==='CPF')q=await env.DB.prepare('SELECT * FROM destinatarios WHERE cpf=? LIMIT 10').bind(digits(v)).all();else q=await env.DB.prepare('SELECT * FROM destinatarios WHERE nome LIKE ? COLLATE NOCASE ORDER BY nome LIMIT 10').bind('%'+v+'%').all();return ok(withExp(s,{destinatarios:q.results||[]}),'Consulta concluída.',o)}
async function updateDestinatario(d,env,o){const s=await requireSession(d,env,o),id=clean(d.id);if(!id)return fail('DADOS_INVALIDOS','Destinatário inválido.',400,o);const old=await env.DB.prepare('SELECT * FROM destinatarios WHERE id=?').bind(id).first();if(!old)return fail('DESTINATARIO_NAO_ENCONTRADO','Destinatário não encontrado.',404,o);const upd={posto_graduacao:clean(d.posto_graduacao),telefone:digits(d.telefone),unidade:clean(d.unidade),status:upper(d.status)||'ATIVO'};await env.DB.prepare('UPDATE destinatarios SET posto_graduacao=?,telefone=?,unidade=?,status=?,atualizado_em=? WHERE id=?').bind(upd.posto_graduacao,upd.telefone,upd.unidade,upd.status,now(),id).run();await audit(env,s,'ATUALIZAR','DESTINATARIO',id,old,upd);return ok(withExp(s,{destinatario:Object.assign({},old,upd)}),'Destinatário atualizado.',o)}
async function createAudiencia(d,env,o){const s=await requireSession(d,env,o),a=d.audiencia||{},rec=Array.isArray(a.destinatarios)?a.destinatarios:[];if(!clean(a.processo)||!clean(a.assunto)||!clean(a.data_hora)||!clean(a.modalidade))return fail('DADOS_INVALIDOS','Preencha os campos obrigatórios.',400,o);if(upper(a.modalidade)==='PRESENCIAL'&&!clean(a.local))return fail('LOCAL_OBRIGATORIO','Informe o local.',400,o);if(!rec.length)return fail('DESTINATARIO_OBRIGATORIO','Adicione ao menos um militar.',400,o);const id=crypto.randomUUID(),stamp=now();const day=stamp.slice(0,10).replace(/-/g,''),count=await env.DB.prepare('SELECT COUNT(*) total FROM audiencias WHERE criado_em LIKE ?').bind(stamp.slice(0,10)+'%').first(),codigo='AUD-'+day+'-'+String(Number(count?.total||0)+1).padStart(3,'0');const stmts=[env.DB.prepare(`INSERT INTO audiencias(id,codigo,processo,assunto,data_hora,timezone,local,modalidade,link,observacoes,status,criado_em,criado_por,atualizado_em,atualizado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,codigo,clean(a.processo),clean(a.assunto),clean(a.data_hora),env.TIMEZONE||'America/Belem',clean(a.local),upper(a.modalidade),clean(a.link),clean(a.observacoes),'AGENDADA',stamp,s.row.usuario_id,stamp,s.row.usuario_id)];for(const r of rec){const rg=digits(r.rg),cpf=digits(r.cpf),nome=clean(r.nome);if(!rg||!nome)return fail('DESTINATARIO_DADOS_INVALIDOS','Revise RG e Nome.',400,o);let dest=await env.DB.prepare('SELECT * FROM destinatarios WHERE rg=? LIMIT 1').bind(rg).first();let did=dest?.id||crypto.randomUUID();if(dest){stmts.push(env.DB.prepare('UPDATE destinatarios SET nome=?,cpf=?,posto_graduacao=?,telefone=?,unidade=?,status=?,atualizado_em=? WHERE id=?').bind(nome,cpf,clean(r.posto_graduacao),digits(r.telefone),clean(r.unidade),'ATIVO',stamp,did))}else{stmts.push(env.DB.prepare('INSERT INTO destinatarios(id,nome,telefone,identificacao,unidade,status,criado_em,atualizado_em,rg,cpf,posto_graduacao) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(did,nome,digits(r.telefone),rg,clean(r.unidade),'ATIVO',stamp,stamp,rg,cpf,clean(r.posto_graduacao)))}stmts.push(env.DB.prepare('INSERT INTO audiencia_destinatarios(id,audiencia_id,destinatario_id,status,criado_em,criado_por) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,did,'ATIVO',stamp,s.row.usuario_id))}await env.DB.batch(stmts);await audit(env,s,'CRIAR','AUDIENCIA',id,null,{codigo});return ok(withExp(s,{audiencia:{id,codigo}}),'Audiência cadastrada com sucesso.',o)}
async function listUsuarios(d,env,o){const s=await requireSession(d,env,o);requireAdmin(s);const r=await env.DB.prepare(`SELECT id,nome,login,perfil,status,ultimo_login,criado_em,atualizado_em,tipo_conta,troca_senha_pendente,tentativas_falhas,bloqueado_ate,CASE WHEN bloqueado_ate IS NOT NULL AND bloqueado_ate>? THEN 1 ELSE 0 END bloqueado FROM usuarios ORDER BY nome COLLATE NOCASE`).bind(now()).all();return ok(withExp(s,{usuarios:(r.results||[]).map(x=>Object.assign(x,{troca_senha_pendente:Boolean(x.troca_senha_pendente),bloqueado:Boolean(x.bloqueado)}))}),'Usuários consultados.',o)}
async function passwordMaterial(env,password){if(clean(password).length<8)throw Object.assign(new Error('A senha deve possuir pelo menos 8 caracteres.'),{code:'SENHA_INVALIDA',status:400});const salt=hex(crypto.getRandomValues(new Uint8Array(32)));return {salt,hash:await legacyPasswordHash(password,salt,env.PASSWORD_PEPPER)}}
async function createUsuario(d,env,o){const s=await requireSession(d,env,o);requireAdmin(s);const u=d.usuario||{},login=clean(u.login).toLowerCase(),perfil=upper(u.perfil)||'ADMINISTRADOR';if(!clean(u.nome)||!login)return fail('DADOS_INVALIDOS','Nome e login são obrigatórios.',400,o);if(perfil==='DEV'&&u.confirmar_dev!==true)return fail('CONFIRMACAO_DEV','Confirme explicitamente a criação do perfil DEV.',400,o);const exists=await env.DB.prepare('SELECT id FROM usuarios WHERE lower(login)=?').bind(login).first();if(exists)return fail('LOGIN_EM_USO','Login já cadastrado.',409,o);const p=await passwordMaterial(env,String(u.senha||'')),id=crypto.randomUUID(),stamp=now();await env.DB.prepare(`INSERT INTO usuarios(id,nome,login,perfil,status,senha_hash,salt,criado_em,atualizado_em,tipo_conta,troca_senha_pendente) VALUES(?,?,?,?,?,?,?,?,?,?,1)`).bind(id,clean(u.nome),login,perfil,'ATIVO',p.hash,p.salt,stamp,stamp,upper(u.tipo_conta)||'INDIVIDUAL').run();await audit(env,s,'CRIAR','USUARIO',id,null,{login,perfil});return ok(withExp(s,{usuario_id:id}),'Usuário criado.',o)}
async function updateUsuario(d,env,o){const s=await requireSession(d,env,o);requireAdmin(s);const id=clean(d.usuario_id),u=d.usuario||{},old=await env.DB.prepare('SELECT * FROM usuarios WHERE id=?').bind(id).first();if(!old)return fail('USUARIO_NAO_ENCONTRADO','Usuário não encontrado.',404,o);const perfil=upper(u.perfil)||old.perfil;if(perfil==='DEV'&&u.confirmar_dev!==true)return fail('CONFIRMACAO_DEV','Confirme explicitamente o perfil DEV.',400,o);const login=clean(u.login||old.login).toLowerCase(),dup=await env.DB.prepare('SELECT id FROM usuarios WHERE lower(login)=? AND id<>?').bind(login,id).first();if(dup)return fail('LOGIN_EM_USO','Login já cadastrado.',409,o);await env.DB.prepare('UPDATE usuarios SET nome=?,login=?,perfil=?,tipo_conta=?,atualizado_em=? WHERE id=?').bind(clean(u.nome||old.nome),login,perfil,upper(u.tipo_conta)||old.tipo_conta,now(),id).run();const ended=(await env.DB.prepare('UPDATE sessoes SET revogada_em=? WHERE usuario_id=? AND revogada_em IS NULL').bind(now(),id).run()).meta?.changes||0;await audit(env,s,'ATUALIZAR','USUARIO',id,old,{login,perfil});return ok(withExp(s,{sessoes_encerradas:ended}),'Usuário atualizado.',o)}
async function userAction(d,env,o,kind){const s=await requireSession(d,env,o);requireAdmin(s);const id=clean(d.usuario_id);if(!id)return fail('DADOS_INVALIDOS','Usuário inválido.',400,o);if(kind==='status'){const st=upper(d.status)==='INATIVO'?'INATIVO':'ATIVO';await env.DB.prepare('UPDATE usuarios SET status=?,atualizado_em=? WHERE id=?').bind(st,now(),id).run();if(st==='INATIVO')await env.DB.prepare('UPDATE sessoes SET revogada_em=? WHERE usuario_id=? AND revogada_em IS NULL').bind(now(),id).run()}else if(kind==='unlock')await env.DB.prepare('UPDATE usuarios SET tentativas_falhas=0,bloqueado_ate=NULL,ultimo_erro_login=NULL,atualizado_em=? WHERE id=?').bind(now(),id).run();else if(kind==='sessions')await env.DB.prepare('UPDATE sessoes SET revogada_em=? WHERE usuario_id=? AND revogada_em IS NULL').bind(now(),id).run();else if(kind==='delete'){if(id===s.row.usuario_id)return fail('OPERACAO_INVALIDA','Não é possível excluir a conta em uso.',400,o);await env.DB.batch([env.DB.prepare('DELETE FROM sessoes WHERE usuario_id=?').bind(id),env.DB.prepare('DELETE FROM passkeys WHERE usuario_id=?').bind(id),env.DB.prepare('DELETE FROM webauthn_challenges WHERE usuario_id=?').bind(id),env.DB.prepare('DELETE FROM usuarios WHERE id=?').bind(id)])}await audit(env,s,kind.toUpperCase(),'USUARIO',id);return ok(withExp(s,{}),'Operação concluída.',o)}
async function resetPassword(d,env,o,self=false){const s=await requireSession(d,env,o);if(!self)requireAdmin(s);const id=self?s.row.usuario_id:clean(d.usuario_id),p=await passwordMaterial(env,String(d.nova_senha||''));await env.DB.prepare('UPDATE usuarios SET senha_hash=?,salt=?,troca_senha_pendente=?,tentativas_falhas=0,bloqueado_ate=NULL,atualizado_em=? WHERE id=?').bind(p.hash,p.salt,self?0:1,now(),id).run();await env.DB.prepare('UPDATE sessoes SET revogada_em=? WHERE usuario_id=? AND revogada_em IS NULL').bind(now(),id).run();await audit(env,s,self?'ALTERAR_SENHA':'RESET_SENHA','USUARIO',id);return ok({},'Senha atualizada.',o)}
async function oficioConfigGet(d,env,o){const s=await requireSession(d,env,o),c=await configMap(env);const ano=Number(c.oficio_ano||new Date().getFullYear()),ultimo=Number(c.oficio_ultimo_numero||0);const out={configurada:Boolean(c.oficio_ano&&c.signatario_nome),oficio_ano:ano,oficio_ultimo_numero:ultimo,oficio_proximo_numero:ultimo+1,signatario_nome:c.signatario_nome||'',signatario_nome_guerra:c.signatario_nome_guerra||'',signatario_posto_graduacao:c.signatario_posto_graduacao||'',signatario_rg:c.signatario_rg||'',signatario_cargo:c.signatario_cargo||''};if(c.signatario_assinatura_r2_key){const a=await r2Base64(env,c.signatario_assinatura_r2_key);if(a)out.signatario_assinatura_data_url=`data:${a.mime};base64,${a.base64}`}return ok(withExp(s,{configuracao:out}),'Configuração consultada.',o)}
async function oficioConfigSave(d,env,o){const s=await requireSession(d,env,o);const keys=['oficio_ano','oficio_ultimo_numero','signatario_nome','signatario_nome_guerra','signatario_posto_graduacao','signatario_rg','signatario_cargo'];for(const k of keys)await setConfig(env,s,k,d[k]??'');const c=await configMap(env);if(d.remover_assinatura===true&&c.signatario_assinatura_r2_key){await env.DOCUMENTOS.delete(c.signatario_assinatura_r2_key);await setConfig(env,s,'signatario_assinatura_r2_key','')}if(clean(d.signatario_assinatura_base64)){const mime=clean(d.signatario_assinatura_mime).toLowerCase();if(mime!=='image/jpeg'&&mime!=='image/png')return fail('FORMATO_INVALIDO','A assinatura deve ser JPG/JPEG ou PNG.',400,o);const ext=mime==='image/png'?'png':'jpg',key=`assinaturas/signatario.${ext}`;await env.DOCUMENTOS.put(key,bytesFromBase64(d.signatario_assinatura_base64),{httpMetadata:{contentType:mime},customMetadata:{nome:clean(d.signatario_assinatura_nome)||`assinatura.${ext}`}});await setConfig(env,s,'signatario_assinatura_r2_key',key)}await audit(env,s,'SALVAR_CONFIG','OFICIO','config');return oficioConfigGet(d,env,o)}
async function oficioReservar(d,env,o){const s=await requireSession(d,env,o),c=await configMap(env),ano=Number(c.oficio_ano||new Date().getFullYear()),ultimo=Number(c.oficio_ultimo_numero||0),numero=ultimo+1,id=crypto.randomUUID(),stamp=now();const aud=await env.DB.prepare('SELECT * FROM audiencias WHERE id=?').bind(clean(d.audiencia_id)).first(),dest=await env.DB.prepare('SELECT * FROM destinatarios WHERE id=?').bind(clean(d.destinatario_id)).first();if(!aud||!dest)return fail('DADOS_INVALIDOS','Audiência ou destinatário não encontrado.',404,o);const dados={audiencia:aud,destinatario:dest,configuracao:c};await env.DB.batch([env.DB.prepare(`INSERT INTO oficios(id,audiencia_id,destinatario_id,numero,ano,status,data_emissao,destino_judicial,trecho_opcional,posto_graduacao,dados_json,criado_em,criado_por,atualizado_em) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,aud.id,dest.id,numero,ano,'RESERVADO',clean(d.data_emissao),clean(d.destino_judicial),clean(d.trecho_opcional),clean(d.posto_graduacao),JSON.stringify(dados),stamp,s.row.usuario_id,stamp),env.DB.prepare(`INSERT INTO configuracoes(chave,valor,atualizado_em,atualizado_por) VALUES('oficio_ultimo_numero',?,?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor,atualizado_em=excluded.atualizado_em,atualizado_por=excluded.atualizado_por`).bind(String(numero),stamp,s.row.usuario_id)]);return ok(withExp(s,{oficio:{id,numero,ano,numero_formatado:String(numero).padStart(3,'0')+'/'+ano,status:'RESERVADO'}}),'Número reservado.',o)}
async function oficioFinalizar(d,env,o){const s=await requireSession(d,env,o),id=clean(d.oficio_id),of=await env.DB.prepare('SELECT * FROM oficios WHERE id=?').bind(id).first();if(!of)return fail('OFICIO_NAO_ENCONTRADO','Ofício não encontrado.',404,o);if(!clean(d.pdf_base64))return fail('PDF_INVALIDO','PDF não informado.',400,o);const key=`oficios/${of.ano}/${String(of.numero).padStart(4,'0')}-${id}.pdf`;await env.DOCUMENTOS.put(key,bytesFromBase64(d.pdf_base64),{httpMetadata:{contentType:'application/pdf'},customMetadata:{nome:clean(d.pdf_nome)||`oficio-${of.numero}-${of.ano}.pdf`}});let pkey=null;if(clean(d.processo_pdf_base64)){pkey=`processos/${of.ano}/${id}.pdf`;await env.DOCUMENTOS.put(pkey,bytesFromBase64(d.processo_pdf_base64),{httpMetadata:{contentType:'application/pdf'},customMetadata:{nome:clean(d.processo_pdf_nome)||'processo.pdf'}})}await env.DB.prepare('UPDATE oficios SET status=?,pdf_nome=?,r2_pdf_key=?,processo_pdf_nome=?,r2_processo_key=?,atualizado_em=? WHERE id=?').bind('GERADO',clean(d.pdf_nome),key,clean(d.processo_pdf_nome),pkey,now(),id).run();await audit(env,s,'FINALIZAR_PDF','OFICIO',id);return ok(withExp(s,{oficio_id:id}),'PDF salvo no R2.',o)}

async function oficioGerar(d,env,o){
  const s=await requireSession(d,env,o),requestId=clean(d.request_id),expected=Number(d.numero_esperado||0);
  if(!requestId||!clean(d.pdf_base64))return fail('DADOS_INVALIDOS','Dados para geração do ofício incompletos.',400,o);
  const existing=await env.DB.prepare('SELECT * FROM oficios WHERE request_id=? LIMIT 1').bind(requestId).first();
  if(existing)return ok(withExp(s,{oficio:{id:existing.id,numero:existing.numero,ano:existing.ano,numero_formatado:String(existing.numero).padStart(3,'0')+'/'+existing.ano,status:existing.status},repetida:true}),'Ofício já processado.',o);
  const c=await configMap(env),ano=Number(c.oficio_ano||new Date().getFullYear()),numero=Number(c.oficio_ultimo_numero||0)+1;
  if(expected&&expected!==numero)return fail('NUMERACAO_ATUALIZADA','A numeração foi atualizada por outra operação. Atualize a prévia e tente novamente.',409,o);
  const aud=await env.DB.prepare('SELECT * FROM audiencias WHERE id=?').bind(clean(d.audiencia_id)).first(),dest=await env.DB.prepare('SELECT * FROM destinatarios WHERE id=?').bind(clean(d.destinatario_id)).first();
  if(!aud||!dest)return fail('DADOS_INVALIDOS','Audiência ou destinatário não encontrado.',404,o);
  const id=crypto.randomUUID(),stamp=now(),key=`oficios/${ano}/${String(numero).padStart(4,'0')}-${id}.pdf`,pkey=clean(d.processo_pdf_base64)?`processos/${ano}/${id}.pdf`:null;
  try{
    await env.DOCUMENTOS.put(key,bytesFromBase64(d.pdf_base64),{httpMetadata:{contentType:'application/pdf'},customMetadata:{nome:clean(d.pdf_nome)||`oficio-${numero}-${ano}.pdf`}});
    if(pkey)await env.DOCUMENTOS.put(pkey,bytesFromBase64(d.processo_pdf_base64),{httpMetadata:{contentType:'application/pdf'},customMetadata:{nome:clean(d.processo_pdf_nome)||'processo.pdf'}});
    const dados={audiencia:aud,destinatario:dest,configuracao:c};
    await env.DB.batch([
      env.DB.prepare(`INSERT INTO oficios(id,audiencia_id,destinatario_id,numero,ano,status,data_emissao,destino_judicial,trecho_opcional,posto_graduacao,dados_json,pdf_nome,processo_pdf_nome,criado_em,criado_por,atualizado_em,r2_pdf_key,r2_processo_key,request_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,aud.id,dest.id,numero,ano,'GERADO',clean(d.data_emissao),clean(d.destino_judicial),clean(d.trecho_opcional),clean(d.posto_graduacao),JSON.stringify(dados),clean(d.pdf_nome),clean(d.processo_pdf_nome),stamp,s.row.usuario_id,stamp,key,pkey,requestId),
      env.DB.prepare(`INSERT INTO configuracoes(chave,valor,atualizado_em,atualizado_por) VALUES('oficio_ultimo_numero',?,?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor,atualizado_em=excluded.atualizado_em,atualizado_por=excluded.atualizado_por`).bind(String(numero),stamp,s.row.usuario_id)
    ]);
    await audit(env,s,'GERAR_PDF','OFICIO',id,null,{numero,ano,request_id:requestId});
    return ok(withExp(s,{oficio:{id,numero,ano,numero_formatado:String(numero).padStart(3,'0')+'/'+ano,status:'GERADO'}}),'Ofício gerado e salvo no R2.',o);
  }catch(e){
    try{await env.DOCUMENTOS.delete(key);if(pkey)await env.DOCUMENTOS.delete(pkey)}catch(_){}
    const again=await env.DB.prepare('SELECT * FROM oficios WHERE request_id=? LIMIT 1').bind(requestId).first();
    if(again)return ok(withExp(s,{oficio:{id:again.id,numero:again.numero,ano:again.ano,numero_formatado:String(again.numero).padStart(3,'0')+'/'+again.ano,status:again.status},repetida:true}),'Ofício já processado.',o);
    throw e;
  }
}
async function processoPdf(d,env,o){const s=await requireSession(d,env,o),of=await env.DB.prepare('SELECT * FROM oficios WHERE id=?').bind(clean(d.oficio_id)).first();if(!of||!of.r2_processo_key)return fail('PDF_NAO_ENCONTRADO','Documento do processo indisponível.',404,o);const a=await r2Base64(env,of.r2_processo_key);if(!a)return fail('PDF_NAO_ENCONTRADO','Documento do processo indisponível.',404,o);return ok(withExp(s,{arquivo:a}),'Documento do processo carregado.',o)}
async function oficioPdf(d,env,o){const s=await requireSession(d,env,o),of=await env.DB.prepare('SELECT * FROM oficios WHERE id=?').bind(clean(d.oficio_id)).first();if(!of||!of.r2_pdf_key)return fail('PDF_NAO_ENCONTRADO','PDF indisponível.',404,o);const a=await r2Base64(env,of.r2_pdf_key);if(!a)return fail('PDF_NAO_ENCONTRADO','PDF indisponível.',404,o);return ok(withExp(s,{arquivo:a}),'PDF carregado.',o)}
async function oficioHistorico(d,env,o){const s=await requireSession(d,env,o);let sql=`SELECT o.*,d.nome militar_nome,d.rg militar_rg,a.processo FROM oficios o LEFT JOIN destinatarios d ON d.id=o.destinatario_id LEFT JOIN audiencias a ON a.id=o.audiencia_id WHERE 1=1`,bind=[];if(clean(d.ano)){sql+=' AND o.ano=?';bind.push(Number(d.ano))}if(clean(d.status)){sql+=' AND o.status=?';bind.push(upper(d.status))}if(clean(d.busca)){sql+=' AND (d.nome LIKE ? OR d.rg LIKE ? OR a.processo LIKE ? OR CAST(o.numero AS TEXT) LIKE ?)';const q='%'+clean(d.busca)+'%';bind.push(q,q,q,q)}sql+=' ORDER BY o.ano DESC,o.numero DESC';const r=await env.DB.prepare(sql).bind(...bind).all();const items=(r.results||[]).map(x=>Object.assign(x,{numero_formatado:String(x.numero).padStart(3,'0')+'/'+x.ano,tem_pdf:Boolean(x.r2_pdf_key),tem_processo_pdf:Boolean(x.r2_processo_key)}));return ok(withExp(s,{itens:items}),'Histórico consultado.',o)}
async function biometriaRegister(d,env,o){const s=await requireSession(d,env,o);if(upper(s.row.tipo_conta)!=='INDIVIDUAL')return fail('BIOMETRIA_NAO_PERMITIDA','Biometria disponível apenas para conta individual.',403,o);const cid=clean(d.credential_id),dt=clean(d.device_token);if(!cid||!dt)return fail('DADOS_INVALIDOS','Dados biométricos incompletos.',400,o);const dh=await hmacHex(env.SESSION_SECRET,dt);await env.DB.prepare(`INSERT INTO passkeys(credential_id,usuario_id,public_key,sign_count,transports,dispositivo,rp_id,criado_em,ultimo_uso_em,revogada_em,device_token_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(credential_id) DO UPDATE SET usuario_id=excluded.usuario_id,dispositivo=excluded.dispositivo,ultimo_uso_em=excluded.ultimo_uso_em,revogada_em=NULL,device_token_hash=excluded.device_token_hash`).bind(cid,s.row.usuario_id,'PRF_DEVICE_TOKEN',0,'platform',clean(d.dispositivo),new URL(String(env.FRONTEND_ORIGIN).split(',')[0]).hostname,now(),now(),null,dh).run();return ok(withExp(s,{}),'Biometria ativada.',o)}
async function biometriaLogin(d,env,o){const cid=clean(d.credential_id),dt=clean(d.device_token);if(!cid||!dt)return fail('BIOMETRIA_INVALIDA','Biometria inválida.',401,o);const p=await env.DB.prepare(`SELECT p.*,u.* FROM passkeys p JOIN usuarios u ON u.id=p.usuario_id WHERE p.credential_id=? AND p.revogada_em IS NULL LIMIT 1`).bind(cid).first();if(!p||upper(p.status)!=='ATIVO'||upper(p.tipo_conta)!=='INDIVIDUAL')return fail('BIOMETRIA_INVALIDA','Biometria inválida.',401,o);const dh=await hmacHex(env.SESSION_SECRET,dt);if(!safeEqual(dh,p.device_token_hash))return fail('BIOMETRIA_INVALIDA','Biometria inválida.',401,o);const sess=await createSessionForUser(env,p);await env.DB.prepare('UPDATE passkeys SET ultimo_uso_em=? WHERE credential_id=?').bind(now(),cid).run();return ok({usuario:userDto(p),sessao:sess},'Login biométrico realizado.',o)}
async function biometriaRemove(d,env,o){const s=await requireSession(d,env,o);await env.DB.prepare('UPDATE passkeys SET revogada_em=? WHERE usuario_id=? AND revogada_em IS NULL').bind(now(),s.row.usuario_id).run();return ok(withExp(s,{}),'Biometria removida.',o)}
async function notificacoesList(d,env,o){const s=await requireSession(d,env,o);const r=await env.DB.prepare(`SELECT n.*,o.numero,o.ano,o.pdf_nome,o.r2_pdf_key,o.processo_pdf_nome,o.r2_processo_key,d.nome militar_nome,d.rg militar_rg,d.telefone whatsapp,d.unidade,d.posto_graduacao,d.status destinatario_status,a.processo,a.data_hora,a.local,a.modalidade FROM notificacoes n LEFT JOIN oficios o ON o.id=n.oficio_id LEFT JOIN destinatarios d ON d.id=n.destinatario_id LEFT JOIN audiencias a ON a.id=n.audiencia_id ORDER BY n.criado_em DESC`).all();const itens=(r.results||[]).map(x=>Object.assign(x,{numero_oficio:x.numero?String(x.numero).padStart(3,'0')+'/'+x.ano:'',pdf_disponivel:Boolean(x.r2_pdf_key),processo_pdf_disponivel:Boolean(x.r2_processo_key)})),resumo={pendentes:0,enviadas:0,confirmadas:0,erros:0};for(const x of itens){const st=upper(x.status);if(st==='PENDENTE')resumo.pendentes++;if(st==='ENVIADO'||st==='SIMULADA')resumo.enviadas++;if(st==='CONFIRMADO')resumo.confirmadas++;if(st==='FALHOU')resumo.erros++}return ok(withExp(s,{itens,resumo,modo:'TEST'}),'Notificações consultadas.',o)}
async function dispatch(d,env,o){switch(clean(d.action)){case'health':return routeHealth(env,o);case'login':return routeLogin(d,env,o);case'session':return routeSession(d,env,o);case'logout':return routeLogout(d,env,o);case'audiencias_list':return listAudiencias(d,env,o);case'audiencias_create':return createAudiencia(d,env,o);case'destinatarios_list':return listDestinatarios(d,env,o);case'destinatarios_lookup':return lookupDestinatarios(d,env,o);case'destinatarios_update':return updateDestinatario(d,env,o);case'usuarios_list':return listUsuarios(d,env,o);case'usuarios_create':return createUsuario(d,env,o);case'usuarios_update':return updateUsuario(d,env,o);case'usuarios_status':return userAction(d,env,o,'status');case'usuarios_unlock':return userAction(d,env,o,'unlock');case'usuarios_end_sessions':return userAction(d,env,o,'sessions');case'usuarios_delete':return userAction(d,env,o,'delete');case'usuarios_reset_password':return resetPassword(d,env,o,false);case'password_change_self':return resetPassword(d,env,o,true);case'oficios_config_get':return oficioConfigGet(d,env,o);case'oficios_config_save':return oficioConfigSave(d,env,o);case'oficios_reservar':return oficioReservar(d,env,o);case'oficios_pdf_finalizar':return oficioFinalizar(d,env,o);case'oficios_gerar':return oficioGerar(d,env,o);case'oficios_pdf_obter':return oficioPdf(d,env,o);case'oficios_processo_pdf_obter':return processoPdf(d,env,o);case'oficios_historico_list':return oficioHistorico(d,env,o);case'biometria_register':return biometriaRegister(d,env,o);case'biometria_login':return biometriaLogin(d,env,o);case'biometria_remove':return biometriaRemove(d,env,o);case'notificacoes_list':return notificacoesList(d,env,o);default:return fail('ROTA_EM_MIGRACAO','Rota ainda não ativada no backend Cloudflare: '+clean(d.action),501,o)}}
export default{async fetch(req,env){const o=originFor(req,env);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':o,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type'}});try{if(req.method==='GET'){const u=new URL(req.url);return dispatch({action:u.searchParams.get('action')||'health'},env,o)}if(req.method!=='POST')return fail('METODO_INVALIDO','Método não permitido.',405,o);const d=await req.json().catch(()=>({}));return await dispatch(d,env,o)}catch(e){return fail(e.code||'ERRO_INTERNO',e.message||'Erro interno.',e.status||500,o)}}};
